sudo: required

language: java

services:
  - docker

after_success:
  - docker network create --driver bridge se-coursework
  - docker pull mongo
  - docker run -d --name mongo-dbserver --network se-coursework mongo
  - docker build -t semcoursework .
  - docker run --network se-coursework semcoursework¦